version: "2.1"

services:

  server:
    build: ./src/server
    container_name: "server"
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3001"      
    links:
      - db      
    # depends_on:
    #   db:
    #     condition: service_healthy